/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CpaModify;
import controller.ResultModify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cpa;
import model.Result;

/**
 *
 * @author Nam Anh
 */
public class KetQuaPanel extends javax.swing.JPanel {
    Result rs;
    List<Result> resultList = new ArrayList <>();
    DefaultTableModel tableModel1;
    List<Cpa> cpaList = new ArrayList <>();
    DefaultTableModel tableModel2;
    JFrame parentJFrame;
    //MonHocManagePanel mhPanel;     
    /**
     * Creates new form KetQuaPanel
     * @param parentJFrame
     */
    public KetQuaPanel(JFrame parentJFrame) {
        this.parentJFrame = parentJFrame;
        initComponents();
        tableModel1 = (DefaultTableModel) tblResult.getModel(); 
        tableModel2 = (DefaultTableModel) tblCpa.getModel(); 
        showResult();
        showCpa();
        
        //lay cac truong thuoc tinh cua result len txt
    }
    
    public void showResult(){
        resultList = ResultModify.findAll();
        
        tableModel1.setRowCount(0);
        
        resultList.forEach(result -> {
            tableModel1.addRow(new Object[] {tableModel1.getRowCount() + 1, result.getId(), result.getSid(),
                result.getSname(), result.getMidterm(), result.getFinalterm(), result.getCourseGrade(), result.getGrade4()});
        });
    }
    public void showCpa(){
        cpaList = CpaModify.findAll();
        
        tableModel2.setRowCount(0);
        
        cpaList.forEach(cpa -> {
            tableModel2.addRow(new Object[] {tableModel2.getRowCount() + 1, cpa.getId(), cpa.getFullname(),
                cpa.getTongsotc(), cpa.getTctichluy(),cpa.getCpa()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnFindByName1 = new javax.swing.JButton();
        btnFindByID1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMidterm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFinalterm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCpa = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Kết Quả Học Tập");

        btnAdd1.setText("Thêm");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnEdit1.setText("Chỉnh sửa");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete1.setText("Xóa");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnFindByName1.setText("Tìm theo mã HP");
        btnFindByName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByName1ActionPerformed(evt);
            }
        });

        btnFindByID1.setText("Tìm theo MSSV");
        btnFindByID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByID1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã số sinh viên");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã học phần");

        jLabel6.setText("Điểm quá trình");

        jLabel7.setText("Điểm cuối kì");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã số sinh viên", "Mã học phần", "Tên môn học", "Điểm quá trình", "Điểm cuối kì", "Điểm học phần", "Thang 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblResult);

        tblCpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã số sinh viên", "Họ tên", "Tổng số tín chỉ", "Tín chỉ tích lũy", "CPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCpa);

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMidterm, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnEdit1)
                        .addGap(34, 34, 34)
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFindByName1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnFindByID1)
                        .addGap(27, 27, 27)
                        .addComponent(btnRefresh))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalterm, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFinalterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMidterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd1)
                            .addComponent(btnEdit1)
                            .addComponent(btnDelete1)
                            .addComponent(btnFindByName1)
                            .addComponent(btnFindByID1)
                            .addComponent(btnRefresh))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        //        dispose();
        //        AddSubjectFrame addSbjFrame = new AddSubjectFrame();
        //        addSbjFrame.setVisible(true);
//        AddSubjectFrame addFrame = new AddSubjectFrame(this.parentJFrame, this);
//        addFrame.setVisible(true);
//        addFrame.setLocationRelativeTo(null);
//        addFrame.setResizable(false);
        String textID = txtID.getText();
        String sid = txtSID.getText();
        String textMidterm = txtMidterm.getText();
        String textFinalterm = txtFinalterm.getText();
        if (textID.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên trống...");
            return;
        }
         if (sid.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã học phần trống...");
            return;                                      
        }
        int id = 0;
        float midterm = 0, finalterm = 0;
        try {
            id = Integer.parseInt(textID);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên không hợp lệ...");
            return;
        }
        for (Result result : resultList) {
            if (result.getId() == id && result.getSid().equals(sid)) {
                JOptionPane.showMessageDialog(this, "MSSV và Mã học phần đã tồn tại...");
                return;
            }
        }
        try {
            midterm = Float.parseFloat(textMidterm);
            if(midterm < 0 || midterm > 10) {
                JOptionPane.showMessageDialog(this, "Điểm giữa kì không hợp lệ...");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Điểm giữa kì không hợp lệ...");
            return;
        }
        try {
            finalterm = Float.parseFloat(textFinalterm);
            if(finalterm < 0 || finalterm > 10){
                JOptionPane.showMessageDialog(this, "Điểm cuối kì không hợp lệ...");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Điểm cuối kì không hợp lệ...");
            return;
        }

        Result rs = new Result(id, sid, midterm, finalterm);
        ResultModify.insert(rs);
        showResult();
        showCpa();
        JOptionPane.showMessageDialog(this, "Thêm thành công...");

    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        try{
            if(Float.parseFloat(txtMidterm.getText()) >= 0 && Float.parseFloat(txtMidterm.getText()) <= 10)
                rs.setMidterm(Float.parseFloat(txtMidterm.getText()));
            else{
                JOptionPane.showMessageDialog(this, "Điểm giữa kì không hợp lệ...");
                return;
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Điểm giữa kì không hợp lệ...");
            return;
        }
        
        try{
            if(Float.parseFloat(txtFinalterm.getText()) >= 0 && Float.parseFloat(txtFinalterm.getText()) <= 10)
                rs.setFinalterm(Float.parseFloat(txtFinalterm.getText()));
            else{
                JOptionPane.showMessageDialog(this, "Điểm cuối kì không hợp lệ...");
                return;
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Điểm cuối kì không hợp lệ...");
            return;
        }
        
        rs.setCourseGrade();
        rs.setGrade4();
        ResultModify.update(rs);
        showResult();
        showCpa();

    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblResult.getSelectedRow();
        if (selectedIndex >=0) {
            Result rs = resultList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa kết quả này?");
            if (option ==0) {
                ResultModify.delete(rs.getId(),rs.getSid());
                showResult();
                showCpa();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một kết quả...");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnFindByName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByName1ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập mã học phần: ");
        if(input != null && input.length() > 0) {
            resultList = ResultModify.findBySID(input);

                tableModel1.setRowCount(0);

                resultList.forEach((result) -> {
                    tableModel1.addRow(new Object[]{tableModel1.getRowCount() + 1, result.getId(), result.getSid(),
                        result.getSname(), result.getMidterm(), result.getFinalterm(), result.getCourseGrade()});
                });
        }
        else {
            
            JOptionPane.showMessageDialog(this, "Mã học phần trống...");
        }
    }//GEN-LAST:event_btnFindByName1ActionPerformed

    private void btnFindByID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByID1ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập mã số sinh viên: ");
        if(input != null && input.length() > 0) {
            try {
                int id = Integer.parseInt(input);
                resultList = ResultModify.findByID(id);

                tableModel1.setRowCount(0);

                resultList.forEach((result) -> {
                    tableModel1.addRow(new Object[]{tableModel1.getRowCount() + 1, result.getId(), result.getSid(),
                        result.getSname(), result.getMidterm(), result.getFinalterm(), result.getCourseGrade()});
                });
            } catch (Exception e) {
                //showStudent();
                JOptionPane.showMessageDialog(this, "Mã số sinh viên phải là số...");
            }

        } else {
            //showStudent();
            JOptionPane.showMessageDialog(this, "Mã số sinh viên trống...");
        }
    }//GEN-LAST:event_btnFindByID1ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        // TODO add your handling code here:
        int selectedIndex = tblResult.getSelectedRow();
        if (selectedIndex >=0) {
            rs = resultList.get(selectedIndex);
            txtID.setText(Integer.toString(rs.getId()));
            txtSID.setText(rs.getSid());
            txtMidterm.setText(Float.toString(rs.getMidterm()));
            txtFinalterm.setText(Float.toString(rs.getFinalterm()));
            
        }
    }//GEN-LAST:event_tblResultMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtSID.setText("");
        txtMidterm.setText("");
        txtFinalterm.setText("");
        showResult();
        showCpa();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnFindByID1;
    private javax.swing.JButton btnFindByName1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCpa;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtFinalterm;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMidterm;
    private javax.swing.JTextField txtSID;
    // End of variables declaration//GEN-END:variables
}
