/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SubjectModify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Subject;

/**
 *
 * @author Nam Anh
 */
public class MonHocManagePanel extends javax.swing.JPanel {
    DefaultTableModel tableModel1;
    List<Subject> subjectList = new ArrayList <>();
    static Subject s;
    private JFrame parentJFrame;
    /**
     * Creates new form MonHocManagePanel
     * @param parentFrame
     */
    public MonHocManagePanel(JFrame parentFrame) {
        this.parentJFrame = parentFrame;
        initComponents();
        
        tableModel1 = (DefaultTableModel) tblSubject.getModel(); 
        showSubject();
    }
    public void refresh(){
        showSubject();
    }
    
    private void showSubject() {
        subjectList = SubjectModify.findAll();
        
        tableModel1.setRowCount(0);
        
        subjectList.forEach(subject -> {
            tableModel1.addRow(new Object[] {tableModel1.getRowCount() + 1, subject.getSid(),subject.getSname(),
                subject.getCredit(), subject.getWeight(), subject.getSchool(), subject.getLecturer()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnFindByName1 = new javax.swing.JButton();
        btnFindByID1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quản lý học phần");

        btnAdd1.setText("Thêm");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnEdit1.setText("Chỉnh sửa");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete1.setText("Xóa");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        btnFindByName1.setText("Theo tên học phần");
        btnFindByName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByName1ActionPerformed(evt);
            }
        });

        btnFindByID1.setBackground(new java.awt.Color(255, 255, 204));
        btnFindByID1.setText("Theo mã học phần");
        btnFindByID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByID1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(btnFindByName1)
                .addGap(99, 99, 99)
                .addComponent(btnFindByID1)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindByName1)
                    .addComponent(btnFindByID1))
                .addGap(22, 22, 22))
        );

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnEdit1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(btnDelete1)
                                .addGap(79, 79, 79)
                                .addComponent(btnRefresh)))))
                .addGap(145, 145, 145))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit1)
                    .addComponent(btnAdd1)
                    .addComponent(btnDelete1)
                    .addComponent(btnRefresh))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã học phần", "Tên học phần", "Số tín chỉ", "Trọng số QT", "Viện", "Giảng viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSubject);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
//        dispose();
//        AddSubjectFrame addSbjFrame = new AddSubjectFrame();
//        addSbjFrame.setVisible(true);
        AddSubjectFrame addFrame = new AddSubjectFrame(this.parentJFrame, this);
        addFrame.setVisible(true);
        addFrame.setLocationRelativeTo(null);
        addFrame.setResizable(false);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
//        dispose();
//        EditSubjectFrame editSbjFrame= new EditSubjectFrame();
//        editSbjFrame.setVisible(true);
        int selectedIndex = tblSubject.getSelectedRow();
        if(selectedIndex >= 0) {
            s = subjectList.get(selectedIndex);
            //dispose();
            EditSubjectFrame editFrame= new EditSubjectFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một học phần...");
        }

    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblSubject.getSelectedRow();
        if (selectedIndex >=0) {
            Subject sbj = subjectList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa học phần này?");

            if (option ==0) {
                SubjectModify.delete(sbj.getSid());
                showSubject();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một học phần...");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnFindByName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByName1ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên học phần cần tìm");
        if(input != null && input.length() > 0) {
            subjectList = SubjectModify.findBySName(input);
            tableModel1.setRowCount(0);
            subjectList.forEach(subject -> {
                tableModel1.addRow(new Object[] {tableModel1.getRowCount() + 1, subject.getSid(),subject.getSname(),
                    subject.getCredit(), subject.getWeight(), subject.getSchool(), subject.getLecturer()});
        });
        }
        else {
            showSubject();
            JOptionPane.showMessageDialog(this, "Tên học phần không được bỏ trống...");
        }
    }//GEN-LAST:event_btnFindByName1ActionPerformed

    private void btnFindByID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByID1ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập mã học phần cần tìm");
        if(input != null && input.length() > 0) {
            subjectList = SubjectModify.findBySID(input);
            tableModel1.setRowCount(0);
            subjectList.forEach(subject -> {
                tableModel1.addRow(new Object[] {tableModel1.getRowCount() + 1, subject.getSid(),subject.getSname(),
                    subject.getCredit(), subject.getWeight(), subject.getSchool(), subject.getLecturer()});
        });
        }
        else {
            showSubject();
            JOptionPane.showMessageDialog(this, "Mã học phần không được bỏ trống...");
        }
    }//GEN-LAST:event_btnFindByID1ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        showSubject();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnFindByID1;
    private javax.swing.JButton btnFindByName1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSubject;
    // End of variables declaration//GEN-END:variables
}
